- job:
    disabled: false
    name: satellite6-standalone-automation
    concurrent: true
    description: |
        <p>Job that runs robottelo on a machine.</p>
        <p>Please make sure to add the following <strong>ssh key</strong> to your server so that this <strong>Jenkins</strong> job can access it.</p>
        <pre>
        ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzoPajR2xtQOAfBebX69Mx9Ee4P/LMqlxQLKvF0bc79/1ayMf3IrmpY1V6JCpABvMV1830I9D9x9Tr8E9zjg2wWT14hhHsrUKSWUsy3doIwz3MtISBZPMig5AizVjH6Wl/t833zgkeHtStCYI/bmJQykj6AgB8/A4L5SRIpNnl1q7V+sw37Rmumaiqu4lRDXyTXY7mlOCuxrus/WcGyVTh2k+oBVqkz2V2s3+Or8Zy2Y441B4z3vF3lE6aoIBwidBVZ1LKaofZDMRf/lu575cI4AB3N5DQvpqwLSc4+HIvog0FdKUo3qMaFgg0KNkYS5fnpDpRDRQnFw7oFnBHiPNqw== jenkins@satellite-jenkins
        </pre>
    node: sat6-rhel
    parameters:
        - choice:
            name: SATELLITE_VERSION
            choices:
                - '6.3'
                - '6.4'
                - '6.2'
                - '6.1'
                - '6.0'
                - 'downstream-nightly'
                - 'upstream-nightly'
            description: Select the Satellite version in order to correctly populate Tools and Capsule URLs.
        - string:
            name: SERVER_HOSTNAME
        - string:
            name: SSH_USER
            default: root
        - string:
            name: FOREMAN_ADMIN_USER
            default: admin
        - string:
            name: FOREMAN_ADMIN_PASSWORD
            default: changeme
        - choice:
            name: TEST_TYPE
            choices:
                - 'tier1'
                - 'tier2'
                - 'tier3'
                - 'api'
                - 'cli'
                - 'ui'
                - 'rhai'
                - 'sys'
                - 'endtoend-api'
                - 'endtoend-cli'
                - 'endtoend-ui'
                - 'all'
                - 'endtoend-all'
                - 'upgrade'
            description: |
                Be aware that the all TEST_TYPE will last for more than 4-5 hours
        - string:
            name: PYTEST_OPTIONS
            description: |
                <p>If you know how to run py.test and want to provide the
                options for a more granular testing you can specify the options
                here. For example <code>tests/foreman/cli/test_activationkey.py
                -k test_positive_create</code> will run all
                test_positive_create variations for Activation Key using
                hammer.</p>
                <p><strong>If this parameter is not blank then the TEST_TYPE
                parameter will be ignored</strong>.</p>
        - string:
            name: PYTEST_MARKS
            default: not stubbed
            description: |
                Specify the py.test marks you want to run or skip when specifying PYTEST_OPTIONS.
        - string:
            name: ROBOTTELO_REPO
            default: https://github.com/SatelliteQE/robottelo.git
            description: |
                You can override this to your robottelo repo, if needed
        - string:
            name: ROBOTTELO_BRANCH
            default: master
            description: |
                You can override this to any branch. Example: 6.1.z
        - string:
            name: ROBOTTELO_WORKERS
            default: '4'
            description: |
                You can override this to other value of your choice.
        - text:
            name: ROBOTTELO_PROPERTIES
            description: |
                <p>You can provide robottelo.properties file content here</p>
                <p><strong>If this parameter is not blank then SERVER_HOSTNAME,
                SSH_USER, FOREMAN_ADMIN_USER and FOREMAN_ADMIN_PASSWORD
                will be ignored</strong></p>
        - choice:
            name: SAUCE_PLATFORM
            choices:
                 - 'no_saucelabs'
                 - 'macOS 10.12'
                 - 'Windows 10'
        - choice:
            name: SAUCE_BROWSER
            choices:
                 - 'firefox'
                 - 'chrome'
                 - 'edge'
                 - 'internet explorer'
    scm:
        - git:
            url: ${ROBOTTELO_REPO}
            branches:
                - origin/${ROBOTTELO_BRANCH}
            skip-tag: true
    wrappers:
        - satellite6-automation-wrappers
        - inject-passwords:
            global: true
            mask-password-params: true
        - satellite6-sauce-ondemand-wrappers
    builders:
        - satellite6-standalone-automation-builders
    publishers:
        - satellite6-automation-publishers
        - satellite6-automation-archiver
