---
- hosts: compose
  become: true
  become_user: compose
  vars:
    compose_output_dir: "/home/compose/composes"
  tasks:
    - debug:
        msg: "Generating for RHEL{{ rhel_version }}"

    - name: 'Find compose symlink'
      stat:
        path: "{{ compose_output_dir }}/latest-Satellite-6.2-RHEL-{{ rhel_version }}"
      register: compose_link
      ignore_errors: yes

    - name: 'Remove old compose'
      file:
        state: absent
        path: "{{ compose_link.stat.lnk_source }}"
      ignore_errors: yes

    - name: "Generate compose"
      shell: "pungi-koji --no-label --config=rhel{{ rhel_version }}.conf --target-dir={{ compose_output_dir }} --skip-phase=test"
      args:
        chdir: "/home/jenkins/satellite-packaging/compose"
