- job:
    name: 'sat6-unit-test-foreman-virt-who-configure'
    project-type: pipeline
    concurrent: true
    build-discarder:
      days-to-keep: 21
      num-to-keep: -1
    parameters:
      - merge_request
    triggers:
      - gitlab_build_on_change
    dsl:
      !include-raw:
        - workflows/lib/branch_map.groovy
        - ./repos/foreman_virt_who_configure.groovy
        - workflows/lib/gitlabEnv.groovy
        - workflows/test/foreman-plugin.groovy
        - workflows/test/foreman-lib.groovy
        - pipelines/lib/rvm.groovy
        - workflows/lib/gitlab.groovy
    notifications:
      - snapper_notifications
